title: Rigor and Reasoning in Research Software (R3Sw)
author: Alper Altuntas, et al.
copyright: 2025
#logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
